---
development:
  cloud_name: epikhdez
  api_key: '748595732486542'
  api_secret: 9otU3VDiftLsixb0BlFD2SLR0L4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: epikhdez
  api_key: '748595732486542'
  api_secret: 9otU3VDiftLsixb0BlFD2SLR0L4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: epikhdez
  api_key: '748595732486542'
  api_secret: 9otU3VDiftLsixb0BlFD2SLR0L4
  enhance_image_tag: true
  static_image_support: false
